
name: build_cygwin

on:
  push:
    paths:
      - ".github/workflows/build_cygwin.yml"
  pull_request:
    paths:
      - ".github/workflows/build_cygwin.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Cygwin
        uses: egor-tensin/setup-cygwin@v3
        with:
          platform: x64
          packages: cmake make gcc-g++ github libiconv-devel zlib-devel clang llvm zip unzip curl sed libpcre-devel libpcre2-devel liblzma-devel gettext gettext-devel libtool automake autoconf po4a patch

      - name: Clone source code
        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
        run: |
          git clone --recurse-submodules --depth=1 https://github.com/affggh/erofs-utils_cygwin.git -b dev erofs
          cd erofs
          git clone https://github.com/CapShift/erofs-utils extract --depth=1
          
      - name: Patch
        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
        run: |
          cd erofs
          sh scripts/patch-all


          
      - name: Repack out
        shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
        run: |
          rm -rf erofs/.git
          zip -r erofs_source.zip erofs
          
      - name: Upload DTBO Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: erofs_source
          path: C:\tools\cygwin\home\runneradmin\erofs_source.zip
